### ISSUE TITLE
New packages

### ISSUE THREAD

**Issue by trafficonese** [nanxstats/awesome-shiny-extensions#4]
There is another alert package `sweetalert` that is not yet in your list.
https://github.com/t4t5/sweetalert

And I also found `ShinySky` although I believe it is not updated anymore, but it might still be worth adding.
https://github.com/AnalytixWare/ShinySky

**Comment by nanxstats** [comment]
hey @trafficonese -the sweetalert library linked above is a JavaScript library instead of an R package, and it is already covered by `shinyalert` and `shinyWidgets`.

and yes, I'm not sure what's going on with `ShinySky` because it hasn't been updated for years (Bootstrap 2 screenshots still) and most of the functionalities are already covered by native shiny or other newer extension packages.
